// <auto-generated />
namespace Stage.AlienTrick.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Versie21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Versie21));
        
        string IMigrationMetadata.Id
        {
            get { return "201902110834082_Versie 2.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
