// <auto-generated />
namespace Stage.AlienTrick.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Versie24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Versie24));
        
        string IMigrationMetadata.Id
        {
            get { return "201902141441481_Versie 2.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
